types = ["age of vikings", "pirates of the seven seas", "roman empire", 
         "medieval knigthts", "way of the samurai", "wild west", "horror", "fantasy", "shakespeare's world"]

odyssey_data = [["age of vikings", "Viking Ship Museum", "museum", "Oslo, Norway"],
                ["age of vikings", "Lofotr Viking Museum", "living museum", "Borg, Norway"],
                ["age of vikings", "Sverd i fjell", "monument", "Stavanger, Norway"],
                ["age of vikings", "Land of Legends", "historical site", "Roskilde, Denmark"],
                ["age of vikings", "JORVIK Viking Centre", "museum", "York, England"],
                ["pirates of the seven seas", "St. Augustine Pirate and Treasure Museum", "museum", "Key West, Florida, U.S.A."],
                ["pirates of the seven seas", "Pirates of Nassau", "museum", "Nassau, Bahamas"],
                ["pirates of the seven seas", "Contraband Days", "festival", "Lake Charles, Louisiana, U.S.A"],
                ["pirates of the seven seas", "Blackbeard's Castle", "historical site", "Charlotte Amalie, U.S. Virgin Islands"],
                ["pirates of the seven seas", "Tortuga Island", "historical destination", "Tortuga Island, Hispaniola"],
                ["roman empire", "Colloseum", "historical site", "Rome, Italy"],
                ["roman empire", "Roman Forum", "historical site", "Rome, Italy"],
                ["roman empire", "Catacombs of Rome", "historical site", "Rome, Italy"],
                ["roman empire", "Torre de Hércules", "lighthouse", "A Coruña, Galicia, Spain"],
                ["roman empire", "Ephesus", "historical site", "Selçuk, Turkey"],
                ["medieval knights", "Tower of London", "historical site", "London, U.K."],
                ["medieval knights", "Mont Sant-Michel", "historical destination", "Normandy, France"],
                ["medieval knights", "Edinburgh Castle", "historical site", "Edinburgh, Scotland"],
                ["medieval knights", "Neuschwanstein Castle", "historical site", "Hohenschwangau, Germany"],
                ["medieval knights", "Alcázar de Segovia", "historical site", "Segovia, Spain"],
                ["way of the samurai", "The Japanese Sword Museum", "museum", "Tokyo, Japan"],
                ["way of the samurai", "Kōga Ninja Village", "historical site", "Koka City, Japan"],
                ["way of the samurai", "Iga-ryu Ninja Museum", "museum", "Iga, Mie Prefecture, Japan"],
                ["way of the samurai", "Himeji Castle", "historical site", "Himeji, Japan"],
                ["way of the samurai", "Nagamachi", "historical destination", "Nagamachi, Kanazawa, Japan"],
                ["wild west", "OK Corral", "historical site", "Tombstone, Arizona, U.S."],
                ["wild west", "San Xavier Mission Church", "religious site", "Tucson, Arizona, U.S."],
                ["wild west", "Old Trail Town", "historical site", "Cody, Wyoming, U.S."],
                ["wild west", "Buckhorn Exchange", "Restaurant", "Denver, Colorado, U.S."],
                ["wild west", "Billy the Kid's Grave", "historical site", "Fort Sumner, New Mexico, U.S."],
                ["horror", "Dracula's Castle", "historical site", "Bran, Romania"],
                ["horror", "Stanley Hotel", "hotel", "Estes Park, Colorado, U.S."],
                ["horror", "Frankenstein Castle", "historical site", "Southern Hesse, Germany"],
                ["horror", "Musee des Vampires", "museum", "Paris, France"],
                ["horror", "Sleepy Hollow", "historical destination", "Sleepy Hollow, New York, U.S."],
                ["fantasy", "Hobbiton Movie Set Tours", "film site", "Auckland, New Zealand"],
                ["fantasy", "Lars Homestead, Tatooine", "film site", "Chott el Djerid, Tunisia"],
                ["fantasy", "Warner Bros. Studio Tour (Harry Potter)", "film site", "London, U.K."],
                ["shakespeare's world", "The Globe Theater", "historical site", "London, U.K."],
                ["shakespeare's world", "Kronborg Castle (Hamlet's Castle)", "historical site", "Helsingor, Denmark"],
                ["shakespeare's world", "Iverness Castle (Macbeth's Castle)", "historical site", "Iverness, Scotland"],
                ["shakespeare's world", "Mount Párnitha National Park (A Midsummer Night's Dream)", "park", "Athens, Greece"],
                ["shakespeare's world", "Juliet's Balcony", "historical site", "Verona, Italy"]]